export const LoadingTypes = {
  OPEN_BUTTON_LOADING: 'OPEN_BUTTON_LOADING',
  CLOSE_BUTTON_LOADING: 'CLOSE_BUTTON_LOADING',
  OPEN_PAGE_LOADING: 'OPEN_PAGE_LOADING',
  CLOSE_PAGE_LOADING: 'CLOSE_PAGE_LOADING'
};
